### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Orestasas** [qubic/wallet-app#10]
To make mobile app feel more consistent with the rest of Qubic ecosystem, we should start by updating following things:
1. Make corner radius of all buttons and input fields 12px
2. Update font to Space Grotesk

**Comment by Qubic-Hub** [comment]
@Orestasas currently Space Grotesk from google fonts is used, is there another Space Grotesk? 
I notice the difference in web and mobile and was also wondering about this too

**Comment by Orestasas** [comment]
@Qubic-Hub strange, there is only one space grotesk font
