### ISSUE TITLE
Update UI of the settings page

### ISSUE THREAD

**Issue by Orestasas** [qubic/wallet-app#107]
To promote consistency we should update the UI of the settings page.
1. Icons should match design
2. Layout & Titles of items should be updated
[Design Here](https://www.figma.com/design/uyqKWH9xX5hOz0BjtuzJ7g/Qubic-Wallet-Mobile-App?node-id=1447-1903&t=LQBiAXPMQmLyhhyb-4)

**Comment by sallymoc** [comment]
I guess Join Community need to be aligned to the new style as well

![Image](https://github.com/user-attachments/assets/e852b32f-8b9e-491b-a59d-1f4ebf16a128)

**Comment by sallymoc** [comment]
Also, I don't see the icon displayed in the red rectangle in the image below in Figma ![Image](https://github.com/user-attachments/assets/ae961853-73cb-4b7a-bcb1-584c26b348be)

**Comment by ahmed-tarek-salem** [comment]
@sallymoc 

This image is from the Figma file, it has the same icon.
This icon usually indicates that you will go to an external link.

<img width="314" alt="image" src="https://github.com/user-attachments/assets/ab0179b0-cdf6-40bf-a860-1c99efadda23">

**Comment by ahmed-tarek-salem** [comment]
@sallymoc 

For the Join Community section, does it have any reference in Figma yet?

**Comment by sallymoc** [comment]
> To promote consistency we should update the UI of the settings page.
> 
> 1. Icons should match design
> 
> 2. Layout & Titles of items should be updated
> 
> [Design Here](https://www.figma.com/design/uyqKWH9xX5hOz0BjtuzJ7g/Qubic-Wallet-Mobile-App?node-id=1447-1903&t=LQBiAXPMQmLyhhyb-4)

Ok, weird that I did not see it. Probably I had the bubbles with the comments on top covering.

Join Community design should be consistent (styling and also the external link icon as all the options open externally) but seems it's not in Figma.
@Orestasas can you please add this to Figma?

**Comment by sallymoc** [comment]
@ahmed-tarek-salem  I've tried in Android Emulator - Small Phone and the results were:

Titles are not centered
Please don't set the version fix at the bottom, make it part of the scrollable content


![Image](https://github.com/user-attachments/assets/c59b6156-a915-4edf-ac5e-5d659152a892)

![Image](https://github.com/user-attachments/assets/ba3caf9a-70c1-43e0-8356-327106ebc2cf)

**Comment by sallymoc** [comment]
It looks fine now. Tested in iPhone 11 and Android Emulator - Small Phone.
I will open a separated issue (low prio) to handle different urls for the privacy policy for each language.
