### ISSUE TITLE
Amount and currency are not bottom aligned in the Resend Trx dialog

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#108]
![image](https://github.com/user-attachments/assets/6741e353-ee37-493c-9995-85885151b557)

**Comment by ahmed-tarek-salem** [comment]
@sallymoc 

How to reproduce?
eg: how to make a failed transaction?

**Comment by sallymoc** [comment]
When creating the trx, you can set the current tick or a tick in the future lower than +5

**Comment by ahmed-tarek-salem** [comment]
I tried to manually override the tick with a future tick (+3), but it gives me this error

![Image](https://github.com/user-attachments/assets/c213613b-7e58-4dc0-b2a8-7914067e9d5e)

**Comment by sallymoc** [comment]
@ahmed-tarek-salem  Please try by setting the +3 in the code
autoCurrentPlus5(5),
to
autoCurrentPlus5(3),

 because I think the current tick shown in that screen is not correct.
You can also try adding two transaction from the same source added to the same tick. Only one transaction per origin can be added to a tick. The latest one added should replace the previous one, so one should fail. That is the theory, but not sure how its handled.

**Comment by sallymoc** [comment]
Tested with the latest state of develop branch and works
