### ISSUE TITLE
Change login area - Apple Store rejection problem

### ISSUE THREAD

**Issue by AndyQus** [qubic/wallet-app#11]
Guideline 2.1 - Information Needed

We have started your beta app's review, but we were unable to successfully access all or part of your app. 

Specifically, we need a wallet password to sign in.

In order for us to continue the review, we need to have a way to verify all app features and functionality. Typically this is done by providing a demo account that has access to all features and functionality in your beta app. It is also acceptable to include a demonstration mode that exhibits your app’s full features and functionality. Note that providing a demo video showing your beta app in use is not enough for us to continue the review.

Next Steps

To help us proceed with the review of your app, please provide a user name and password in the Beta App Review Information section of App Store Connect. Please be sure that the demo account includes content that demonstrates the features and functionality available in your app. 

To provide demo account information:

- Log in to App Store Connect
- Click on "My Apps"
- Select your app
- Navigate to the "TestFlight" tab
- Select "Test Information"
- Scroll down to "Beta App Review Information"
- Select the "Sign-in required" box
- Enter demo credentials in the "User Name" and "Password" fields
- Click "Save"
- Reply to this message in App Store Connect

Support

- Reply to this message in your preferred language if you need assistance. If you need additional support, use the [Contact Us module](https://developer.apple.com/contact/topic/#!/topic/select).
- Consult with fellow developers and Apple engineers on the [Apple Developer Forums](https://developer.apple.com/forums/).
- Help improve the review process or identify a need for clarity in our policies by [suggesting guideline changes](https://developer.apple.com/contact/app-store/?topic=guideline).

![Screenshot-0520-122023](https://github.com/qubic/wallet-app/assets/157237454/2be23695-6367-46f3-b94c-297c7fd25274)

**Comment by sallymoc** [comment]
We will be ready to resubmit the app for review after implemented the following 
![wallet-flows2](https://github.com/qubic/wallet-app/assets/231888/b04afad8-9245-4842-8d1c-888c44586674)
![wallet-flows3](https://github.com/qubic/wallet-app/assets/231888/30ad8098-fb03-40e7-85b0-f681e553ef75)
![wallet-flows1](https://github.com/qubic/wallet-app/assets/231888/0143a05d-b666-4c46-8f91-e2c9b55622a5)

We will update the instructions for the reviewers and will provide an address with some qubic so they can also do transactions

**Comment by sallymoc** [comment]
Flow was updated as described in the comment above. Steps for testing were updated and the apps were approved in both platform. Closing this.
