### ISSUE TITLE
To include an option to "Import Private Seed" when tapping + for New account

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#142]
We currently have in Develop the following sheet when tapping +

![image](https://github.com/user-attachments/assets/cb531d85-3599-41dc-867b-b6c204bc1b44)

The option "Create New Account" will be split in two: "Create New Account" and "Import Private Seed" as shown in the screen below:

![image](https://github.com/user-attachments/assets/c51007f8-7451-4dbb-a12c-a41ffc4f8a0d)

For option 1. there is not possibility, the app generates randomly the private seed and there is not possibility to change it manually.
In option 3. the user have only the option to enter the value manually.

Figma design here https://www.figma.com/design/uyqKWH9xX5hOz0BjtuzJ7g/Qubic-Wallet-Mobile-App?node-id=1347-2025&t=6vEjxwHqcO79lzHW-4

![Image](https://github.com/user-attachments/assets/381c3967-66d2-447a-8c0f-79efb777c15e)

![Image](https://github.com/user-attachments/assets/acb49d48-4246-46e7-9e4d-275b27811232)

**Comment by ahmed-tarek-salem** [comment]
@sallymoc 

In the home, if there are no accounts there is a button called "Add New Account", should it be as option 1 or as option 3?

**Comment by sallymoc** [comment]
Verified in latest 1.2.0 release
