### ISSUE TITLE
To set a default account name for the different add account options

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#149]
The account name field in any of the add account options should be pre-populated with the format: 
"Account {accountNumber}" (en)
"Konto {accountNumber}" (de)
"Cuenta {accountNumber}" (es)
"Hesap {accountNumber}" (tr)
"Аккаунт {accountNumber}" (ru)
"Compte {accountNumber}" (fr)

where N is the number of accounts in the wallet plus 1.

**Comment by ahmed-tarek-salem** [comment]
What should it be for the Chinese file?

**Comment by sallymoc** [comment]
"账户 {accountNumber}"

**Comment by sallymoc** [comment]
This is already live in the stores.
