### ISSUE TITLE
To replace "Public/SubmitTransaction" with https://rpc.qubic.org/v1/broadcast-transaction

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#150]

**Comment by ahmed-tarek-salem** [comment]
@sallymoc 

I can't find this endpoint in the documentation:
v1/broadcast-transaction

https://qubic.github.io/integration/Partners/qubic-rpc-doc.html?urls.primaryName=Qubic%20RPC%20Archive%20Tree

**Comment by sallymoc** [comment]
Verified with the latest status of develop branch as of today.
https://rpc.qubic.org/v1/broadcast-transaction is being called when sending qubics and assets.
