### ISSUE TITLE
To use the verifyAPI to notify end-users when they may be connecting to a suspicious or malicious domain

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#173]
More details here:
https://docs.reown.com/walletkit/best-practices#4-verify-api

@Orestasas  please if you can add in Figma the domain verification information for the unhappy scenarios (domain match case should not show anything).

**Comment by sallymoc** [comment]
Blocked as this requires to update to reown.
Feedback from @ahmed-tarek-salem 

The current package walletconnect_flutter_v2
doesn't support this verifyContext, Reown only does
![Image](https://github.com/user-attachments/assets/95b6bf14-07db-4614-a138-d898e7d5825b)

**Comment by sallymoc** [comment]
I could verify the invalid, valid and unknown cases.
It's complicated to verify the scam case because I don't know which app matches this condition and hardcoding a possible scam url in our dapp results on the domain mistmatch case.
It's no clear to me what is the condition for 'unknown' but I got this with https://stake.lido.fi/ or https://juicybet.net/. Please let know @ahmed-tarek-salem  in case you can provide more info for testing this. Otherwise I would just close this ticket.

**Comment by ahmed-tarek-salem** [comment]
@sallymoc 

You can find some of them here:
https://malicious-app-verify-simulation.vercel.app/

For example:
![image](https://github.com/user-attachments/assets/c0d6c742-6262-4de5-8a6e-001c88bea274)

**Comment by sallymoc** [comment]
Thank you. Verified it and I can close this then.
