### ISSUE TITLE
WalletConnect: To upgrade to Reown WalletKit

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#176]
WalletConnect Inc. is now known as Reown.

https://github.com/WalletConnect/WalletConnectFlutterV2 is no longer maintained.
We need to upgrade to Reown packages.

Some useful documentation about this here:
https://docs.reown.com/walletkit/upgrade/from-web3wallet-flutter

**Comment by ahmed-tarek-salem** [comment]
The new package Reown has two conflicts with our packages:

1- package_info_plus: Reown uses it with version 7.0.0 and we use it with version 8.0.0 (We can't downgrade it at this time)
For this, there is an open issue:
https://github.com/reown-com/reown_flutter/issues/9

2- share_plus: Reown uses web_socket_channel  that depends on web 0.5.0, while share_plus depends on web 1.0.0
For this, I opened a new issue:
https://github.com/reown-com/reown_flutter/issues/10

Downgrading our packages is not a valid option.

So now we have two options:

1- Upgrade to Reown and do manual overriding  for those dependencies (I did it and it worked but it still needs to be tested very well as it might cause run time issues)
2- Keeping  WalletConnect until fixing those two issues in the Reown package

So what do you think?

**Comment by sallymoc** [comment]
Blocked as we wait for the updates in the reown framework.

**Comment by sallymoc** [comment]
Update was done and already some bugs fixes. Other bugs will be reported separately.
