### ISSUE TITLE
To update the UI for the Wallet Connect init session

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#179]
It is currently:

![image](https://github.com/user-attachments/assets/eb5cbe5a-e120-4a2e-aec9-4ae2cdff04cb)

It should be:
https://www.figma.com/design/uyqKWH9xX5hOz0BjtuzJ7g/Qubic-Wallet-Mobile-App?node-id=1301-3984&t=IDZ8ZZtglQmjuEdx-4

**Comment by sallymoc** [comment]
Please also include the following validations:

- Supported network -> https://www.figma.com/design/uyqKWH9xX5hOz0BjtuzJ7g/Qubic-Wallet-Mobile-App?node-id=1905-2240&t=XnMkfCxCKinOUXNJ-4
- url is for walletconnect v1
As reference, I saw Kraken wallet code https://github.com/krakenfx/wallet/blob/main/src/screens/ConnectAppQRScan/components/handleWalletConnectUri.tsx

**Comment by sallymoc** [comment]
@ahmed-tarek-salem  I can't manage to see the screen for the unsupported network. Maybe it's handle differently after the upgrade to reown.
When using a different network, the app just displays an error with the snackbar message in red background for few seconds.

**Comment by ahmed-tarek-salem** [comment]
@sallymoc 

This is a comment from William on Discord about this:


<img width="444" alt="image" src="https://github.com/user-attachments/assets/5633441e-1b10-431b-add8-01fbca8f9979">

**Comment by sallymoc** [comment]
Unsupported network changed message change as snackbar ![Image](https://github.com/user-attachments/assets/5ce49b6b-8cf4-4aeb-b02a-f8571a3c1514)
(we don't have the app information and looks odd to have the full screen message)
