### ISSUE TITLE
As a user, I should be able to change primary value view in a wallet to display it in USD units

### ISSUE THREAD

**Issue by Orestasas** [qubic/wallet-app#187]
Clicking on a $ amount (smaller gray) should switch the primary value (like in the screenshot) and vice versa.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/7d118d6c-a931-4243-85bb-18a95c333683">

<img width="551" alt="image" src="https://github.com/user-attachments/assets/35b600f7-d812-47db-a725-6e309fb6b870">

**Comment by sallymoc** [comment]
Tested in 1.3.0 (75).
