### ISSUE TITLE
To display the watch only icon in the list of accounts in the send qubic and send assets forms

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#200]
Please add the eye icon next to the account name in the account list, similar to how it is shown in the Home tab.
i.e if 'test' account is watch only account

![image](https://github.com/user-attachments/assets/2fbfef19-bc7c-4095-8cb7-6ee447dc7323)

**Comment by pratikbaid3** [comment]
I'd like to contribute to this @sallymoc. Would you be able top assign this to me?

**Comment by sallymoc** [comment]
Fix is live in production
