### ISSUE TITLE
Trying to recover my seed from the 0.9 version of the wallet for Windows

### ISSUE THREAD

**Issue by ChristianOConnor** [qubic/wallet-app#219]
I had a wallet back at the 0.9 version of this app for Windows. Sadly, I tried to copy my seed to my Keepass file, but I accidentally copied my Public ID instead of the seed and never noticed... Now it's several months later, and that version of the wallet appears to be deprecated... So My funds are locked. I tried to open my wallet on my PC but I get the message "Error contacting Qubic Network" and "Exception: Failed to authenticate. Could not parse response"

I copied the contents of `C:\Users\MYUSERNAMEHERE\AppData\Roaming\Qubic-Hub\qubic_wallet` and the contents of this folder are:  
```
PS \Path\To\Qubic-Hub\quibic_wallet> tree .\qubic_wallet\ /f
Folder PATH listing
Volume serial number is CENSORED
\Path\To\Qubic-Hub\quibic_wallet
    Poppins_regular_WHATLOOKSLIKEAHASH.ttf
    qubic-helper-win-x64-2_0_0.exe
    qubic_wallet_COMPLEXSTRINGHERE_QW__CSETTINGS.secure
    qubic_wallet_COMPLEXSTRINGHERE_QW__SETTINGS.secure
    SmoochSans_regular_WHATLOOKSLIKEAHASH.ttf

No subfolders exist

PS \Path\To\Qubic-Hub\quibic-wallet>
```  

I have the password that I used to encrypt the wallet. Is there any way to extract the seed? Or at least migrate the data to a newer working version of the wallet so I can unlock the funds?

**Comment by Vickynicole** [comment]
Hello @ChristianOConnor 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WAL07638
Please see the link below to our dedicated support line:
[Wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sallymoc** [comment]
We don't have a windows version available in this repository. Please @ChristianOConnor  create your issue in the qubic-hub organization.

**Comment by Laurensavage** [comment]
> I had a wallet back at the 0.9 version of this app for Windows. Sadly, I tried to copy my seed to my Keepass file, but I accidentally copied my Public ID instead of the seed and never noticed... Now it's several months later, and that version of the wallet appears to be deprecated... So My funds are locked. I tried to open my wallet on my PC but I get the message "Error contacting Qubic Network" and "Exception: Failed to authenticate. Could not parse response"
> 
> I copied the contents of `C:\Users\MYUSERNAMEHERE\AppData\Roaming\Qubic-Hub\qubic_wallet` and the contents of this folder are:
> 
> ```
> PS \Path\To\Qubic-Hub\quibic_wallet> tree .\qubic_wallet\ /f
> Folder PATH listing
> Volume serial number is CENSORED
> \Path\To\Qubic-Hub\quibic_wallet
>     Poppins_regular_WHATLOOKSLIKEAHASH.ttf
>     qubic-helper-win-x64-2_0_0.exe
>     qubic_wallet_COMPLEXSTRINGHERE_QW__CSETTINGS.secure
>     qubic_wallet_COMPLEXSTRINGHERE_QW__SETTINGS.secure
>     SmoochSans_regular_WHATLOOKSLIKEAHASH.ttf
> 
> No subfolders exist
> 
> PS \Path\To\Qubic-Hub\quibic-wallet>
> ```
> 
> I have the password that I used to encrypt the wallet. Is there any way to extract the seed? Or at least migrate the data to a newer working version of the wallet so I can unlock the funds?




Hello @ChristianOConnor 
Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by ChristianOConnor** [comment]
Gotcha, thanks for the reply.
