### ISSUE TITLE
Zero sized vault file

### ISSUE THREAD

**Issue by pegasus-schreck** [qubic/wallet-app#231]
Using the wallet app on the following platform and it fails to write a proper vault file.  It works fine on my iPhone however when using the app on my Macbook Pro with the following OS version 14.6.1 (23G93) an attempt to write the vault file results in a zero byte sized file and doesn't allow import into the webapp.

**Comment by Jasonwyat** [comment]
Hello @pegasus-schreck 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WAL07638
Please see the link below to our dedicated support line:
[Wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sallymoc** [comment]
Hello @pegasus-schreck 
Do you see any error alert during the generation of the file? did you see any alert when running for the first time?
Also, does the import wallet (generated from web or from mobile) work?
Might I please also ask you which version are you using? if you see this with 1.2.1, might you please also try with 1.2.0 and let us know the result.
Tested with 15.0 (24A335), seems import and export are working fine.

**Comment by pegasus-schreck** [comment]
@sallymoc it is indeed version 1.2.1.  It does occasionally throw connection errors but in the end the balance updates and seems to do what it is supposed to do.  I will try version 1.2.0 tomorrow.  It does not throw any type of error when generating the vault file, I will also say the version on my iPhone runs flawlessly and that is also v 1.2.1.  The import from mobile works as anticipated which is how I was able to participate in QEarn.

**Comment by sallymoc** [comment]
Discussed internally with @pegasus-schreck  in Discord.  We can close this, the version used was the iPad one running in the computer (downloaded from Apple Store). When running the mac version (https://github.com/qubic/wallet-app/releases/download/v1.2.1/app-mac.zip) it works. We can close this.
