### ISSUE TITLE
iOS Wallet not displaying Qubic Amount

### ISSUE THREAD

**Issue by Toddizzzle** [qubic/wallet-app#36]
User confirms they imported their seedphrase into the iOS wallet and are not able to see their balance. They confirmed their Address ID matches and see the balance in the Web Wallet with no issues.
![image](https://github.com/qubic/wallet/assets/174657072/0927e533-db2c-41d4-8747-b1975b112dc0)

**Comment by sallymoc** [comment]
I contacted the user in Discord and waiting for feedback.

**Comment by sallymoc** [comment]
@Toddizzzle so far, I didn't receive any answer from the user

**Comment by sallymoc** [comment]
Can't reproduce and no feedback receive from the reporter on this.

**Comment by elcidcampeadorcristiano** [comment]
@sallymoc, I have very similar same issue: I cannot see my web wallet amount, but my IOS wallet runs perfectly. 
About the issue of web wallet, I unlocked it because I can reveal the seed of my directions, but, cannot see the amount of qubic, and neither can Qern nothing.
