### ISSUE TITLE
URL rename block -> tick to explorer.qubic.org

### ISSUE THREAD

**Issue by AndyQus** [qubic/wallet-app#4]
Only when it is implemented in Explorer.

https://explorer.qubic.org/network/block/13299929
in
https://explorer.qubic.org/network/tick/13299929

- explorer.qubic.org version 1.2 start 14. April
- the old Explorer is still accessible
-

**Comment by sallymoc** [comment]
Hello @AndyQus  is this valid for the wallet app?
Afak we don't use those urls.

**Comment by AndyQus** [comment]
very good, then the ticket can be closed.
