### ISSUE TITLE
Change and adapt the content under wallets on the qubic.org website

### ISSUE THREAD

**Issue by AndyQus** [qubic/wallet-app#5]

**Comment by sallymoc** [comment]
@AndyQus  do you refer to this 
![image](https://github.com/user-attachments/assets/caba2bf9-ec54-40e3-bd1f-2be13ee63f74) ?

@Orestasas  is there any change/improvement that you would like to do for it?

**Comment by AndyQus** [comment]
@sallymoc Yes that was it.
