### ISSUE TITLE
Settings screen is not scrollable and user can't access to the settings options at the bottom of the screen in small screen devices

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#58]
![image](https://github.com/user-attachments/assets/27f53e47-c154-4b37-8d3f-14304ad1a6b9)
The screenshot above was taken with Android Emulator - Small Phone

In iPhone SE, it looks like this 
![image](https://github.com/user-attachments/assets/8fdd2009-590f-4e5a-8022-42d5ad14159e)
It is possible to scroll to see the options, but can't keep the offset.

https://github.com/user-attachments/assets/950c9995-30fe-4165-989e-771ee071c12d

**Comment by Qubic-Hub** [comment]
Fixed with https://github.com/qubic/wallet-app/pull/63
