### ISSUE TITLE
To support biometric authentication for the Mac OS app

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#70]
The method used to check if the device supports/has configured biometric authentication is apparently not available for Mac OS

![image](https://github.com/user-attachments/assets/7abaf41b-22ed-4a9a-af44-5a0b05c799f5)

Connecting to VM Service at ws://127.0.0.1:63950/F2pbDHYazKw=/ws
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:520:35)
<asynchronous suspension>
#2      DefaultLocalAuthPlatform.deviceSupportsBiometrics (package:local_auth_platform_interface/default_method_channel_platform.dart:65:10)
<asynchronous suspension>
#3      _SignInState.initState.<anonymous closure> (package:qubic_wallet/pages/auth/sign_in.dart:78:35)
<asynchronous suspension>

I found this https://github.com/flutter/flutter/issues/140685 that might be useful.

**Comment by depombo** [comment]
following

**Comment by Qubic-Hub** [comment]
@sallymoc  According to https://pub.dev/packages/local_auth  it seems that MacOS is now supported. Maybe we need to update ?

**Comment by sallymoc** [comment]
Correct @Qubic-Hub  . With this config in the yaml file 

local_auth: ^2.3.0

is 'works'. I have some issues when debugging but seems not to be related to the library itself and happening only in debug mode. Need to test a bit more.

**Comment by sallymoc** [comment]
With the upgrade of the library, iOS authentication in release mode works fine. Debug mode is failing with or without this change. I reported the following issue https://github.com/qubic/wallet-app/issues/92.

**Comment by sallymoc** [comment]
@icyblob could you please try this and let us know if works for you so we can close it?
