### ISSUE TITLE
To display the current MarketCap as in the web wallet

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#74]
From product-feedback channel
https://discord.com/channels/768887649540243497/1257429576313864323/1260494590675255306

![image](https://github.com/user-attachments/assets/66da9072-72e6-4032-90cf-8ebbbf2d9ab9)

**Comment by sallymoc** [comment]
@Orestasas do you think this can be added?

**Comment by Orestasas** [comment]
@sallymoc would be nice to add it as a part of the explorer page update. I can work on it

**Comment by sallymoc** [comment]
In web wallet it's displayed in the Dashboard 
![image](https://github.com/user-attachments/assets/ea0b101a-bbc7-4c25-8e67-71804223f164)

I've create another ticket to evaluate to replace the current flutter explorer with the web version embedded https://github.com/qubic/wallet-app/issues/80

**Comment by sallymoc** [comment]
I think the replacement will have to wait a bit due to some 'technical' reasons.
This is the current Explorer screen (flutter implementation) 
![image](https://github.com/user-attachments/assets/4ffff897-55f9-4fa5-aa09-b1b47c3ab8d8)

Maybe, as you @Orestasas  suggested initially, can we add the market cap and price  in the first row in the "Overview" section, similar to what web explorer currently does 
![image](https://github.com/user-attachments/assets/489e6cb1-3409-4dcc-8293-de391946126d)

I think we have already the data available and no need to change the current design we have in the mobile app, as a temporary solution.

**Comment by sallymoc** [comment]
@Orestasas  something like this 
![image](https://github.com/user-attachments/assets/d4e38d62-dd93-451b-9619-d1723617eac0)
?

**Comment by Orestasas** [comment]
@sallymoc yes, that works

**Comment by sallymoc** [comment]
Verified in internal testing build 1.2.0 (50) and works as expected 
![image](https://github.com/user-attachments/assets/121b8950-468e-4b0f-8849-7f463df34c68)
