### ISSUE TITLE
To improve the 'pull to refresh' animation in the screens where this action is supported

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet-app#82]

**Comment by Qubic-Hub** [comment]
@sallymoc can we have a recording of the problem? I tested it on iPhone and it seemed ok

**Comment by sallymoc** [comment]
Native iOS vs qubic wallet (material design, more android style)
https://github.com/user-attachments/assets/951c3da9-a78d-4506-b76b-5b7d342b482f

https://github.com/user-attachments/assets/f370e453-8f75-4559-ae19-5954cd753570

**Comment by sallymoc** [comment]
Currently the Total balance header doesn’t move. Following iOS pattern, all content on page should move when doing the pull to refresh gesture. 
The refresh view appears animated from the top of the screen and on top of any other view (see Transfers tab). When there is a navigation bar, it should appear from the bottom of the navigation bar only.

**Comment by sallymoc** [comment]
Sometimes the animation still looks a bit weird and overlaps the contents as can be seen here:
![Image](https://github.com/user-attachments/assets/d5242bf7-6aa1-4f9f-aa9b-813a50f6cb35)

But I couldn't find a consistent way to reproduce this.
The current state is acceptable and we won't spend more time on it because the UI for that screen will be probably updated soon anyway.

Tested in 1.2.0 (59)
